version: "3.8"
services:
  chirpstack:
    image: chirpstack/chirpstack:4.10
    command: -c /etc/chirpstack
    restart: unless-stopped
    environment:
      - POSTGRESQL_HOST=postgresql
      - REDIS_HOST=redis:6379
      - MQTT_BROKER_HOST=mqtt
      - LOG_LEVEL=warn
      - API_SECRET=${CHIRPSTACK_API_SECRET}
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      # - ./lorawan-devices:/opt/lorawan-devices
    depends_on:
      - postgresql
      - mosquitto
      - redis
    ports:
      - 8080:8080
    networks:
      - loragatenet

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:4.0
    # ports:
    #   - 1700:1700/udp
    # volumes:
    #   - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      - INTEGRATION__MQTT__AUTH__GENERIC__SERVERS=tcp://mosquitto:1883
      - GENERAL__LOG_LEVEL=4
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/command/#
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
    depends_on: 
      - mosquitto
    networks:
      - loragatenet
    restart: unless-stopped

  postgresql:
    image: postgres:14-alpine
    # image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root 
      - POSTGRES_DEV_EUI=${CHIRPSTACK_DEV_EUI}
      - POSTGRES_DEV_KEY=${CHIRPSTACK_DEV_KEY}
      - POSTGRES_HASH=${CHIRPSTACK_HASH}
    volumes:
      - ./configuration/postgresql2/initdb:/docker-entrypoint-initdb.d
      - postgresqldata2:/var/lib/postgresql/data
    networks:
      - loragatenet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d chirpstack --username=chirpstack || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 1
      start_period: 15s
      disable: true

  redis:
    image: redis:7-alpine
    # image: redis:5-alpine
    volumes:
      - redisdata:/data
    networks:
      - loragatenet
    restart: unless-stopped
    command: [
            "sh", "-c",
            '
            docker-entrypoint.sh
            --appendonly "yes"
            --notify-keyspace-events "KEA"
            '
    ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 1
      start_period: 15s
      disable: true

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt
    # ports:
    #   - 1883:1883
    networks:
      - loragatenet
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      # - ./mosquitto/passwd:/mosquitto/passwd:ro
      - mdata:/mosquitto/data
      - mlog:/mosquitto/log
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -C 1 -t '#' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 1
      start_period: 15s
      disable: true

  gateway_fwd:
    # build: gateway-forwarder
    image: ghcr.io/lorabridge/gateway-forwarder:latest
    restart: unless-stopped
    volumes:
      # bind mount necessary gpio stuff
      - /sys/class/gpio:/sys/class/gpio
      - /sys/devices/platform/soc/fe200000.gpio:/sys/devices/platform/soc/fe200000.gpio
      - type: volume
        source: gpio
        target: /sys/devices/platform/soc/soc:firmware/soc:firmware:gpio
      # - type: bind
      #   source: /sys/devices/platform/soc/soc:firmware/soc:firmware:gpio
      #   target: /sys/devices/platform/soc/soc:firmware/soc:firmware:gpio
    environment:
      - TZ=Europe/Vienna
      # - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/ttyUSB0
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
    #   - /dev/gpiomem:/dev/gpiomem
      # - /dev/mem:/dev/mem
      # - /dev/ttyAMA0:/dev/ttyAMA0
    # privileged: true
    # cap_add:
    #   - SYS_RAWIO
    group_add:
      - "999"
      - "997"
      # - spi
      # - gpio
    # user: 1337:1337
    networks:
      - loragatenet
    depends_on:
      - chirpstack-gateway-bridge

  homeassistant:
    # build: gateway-home-assistant
    image: ghcr.io/lorabridge/gateway-home-assistant:latest
    container_name: homeassistant
    # image: "ghcr.io/home-assistant/home-assistant:stable"
    depends_on: 
      - mosquitto
    volumes:
      - homeassistant_data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    # privileged: true
    networks:
      - loragatenet
    ports:
      - 8123:8123

  converter:
    # build: gateway-converter
    image: ghcr.io/lorabridge2/gateway-converter:latest
    environment:
      - CON_MQTT_USERNAME=${MQTT_USERNAME}
      - CON_MQTT_PASSWORD=${MQTT_PASSWORD}
      - CON_MQTT_HOST=${MQTT_HOST}
      - CON_MQTT_PORT=${MQTT_PORT}
      - CON_CHIRP_TOPIC=${CHIRP_TOPIC}
      # - CON_DEV_MAN_TOPIC=${DEV_MAN_TOPIC}
      - DEV_REDIS_HOST=${REDIS_HOST}
      - DEV_REDIS_PORT=${REDIS_PORT}
      - DEV_REDIS_DB=${REDIS_DB}
      - DEV_EUI=${CHIRPSTACK_DEV_EUI}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - loragatenet
    volumes:
      - device:/device
    depends_on:
      - mosquitto
      - redis

  ha_integration:
    # build: gateway-ha_integration
    image: ghcr.io/lorabridge2/gateway-ha_integration:latest
    environment:
      - HA_MQTT_USERNAME=${MQTT_USERNAME}
      - HA_MQTT_PASSWORD=${MQTT_PASSWORD}
      - HA_MQTT_HOST=${MQTT_HOST}
      - HA_MQTT_PORT=${MQTT_PORT}
      - HA_STATE_TOPIC=${DEV_STATE_TOPIC}
      - HA_DISCOVERY_TOPIC=${DEV_DISCOVERY_TOPIC}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - loragatenet
    depends_on:
      - mosquitto

  device_manager:
    # build: gateway-device_manager
    image: ghcr.io/lorabridge2/gateway-device_manager:latest
    environment:
      - DEV_MQTT_USERNAME=${MQTT_USERNAME}
      - DEV_MQTT_PASSWORD=${MQTT_PASSWORD}
      - DEV_MQTT_HOST=${MQTT_HOST}
      - DEV_MQTT_PORT=${MQTT_PORT}
      - DEV_MAN_TOPIC=${DEV_MAN_TOPIC}
      - DEV_REDIS_HOST=${REDIS_HOST}
      - DEV_REDIS_PORT=${REDIS_PORT}
      - DEV_REDIS_DB=${REDIS_DB}
      - DEV_STATE_TOPIC=${DEV_STATE_TOPIC}
      - DEV_DISCOVERY_TOPIC=${DEV_DISCOVERY_TOPIC}
      - DEV_EUI=${CHIRPSTACK_DEV_EUI}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - device:/device
    networks:
      - loragatenet
    depends_on:
      mosquitto:
        condition: service_started
      redis:
        condition: service_started
      chirp_helper:
        condition: service_completed_successfully
  flow_ui:
    # build:
    #   context: bridge-device-interface
    #   args:
    #     VITE_SSE_ADDR: http://sse:8080
    #     VITE_REDIS_CONN_STRING: redis://redis:6379
    # image: localhost/flow-ui:latest
    image: ghcr.io/lorabridge2/gateway-flow-ui:latest
    depends_on:
      - redis
      - couchdb
    restart: unless-stopped
    networks:
      - loragatenet
    ports:
      - "3000:3000"
    # expose:
    #   - 3000
    user: 1337:1337
    environment:
      - PUBLIC_COUCHDB_USER=${COUCHDB_USER}
      - PUBLIC_COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - PUBLIC_COUCHDB_PORT=${COUCHDB_PORT}
      - PUBLIC_COUCHDB_DB=${COUCHDB_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    read_only: true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -O - http://127.0.0.1:3000/device_attributes/health --spider -q || exit 1"
        ]
      interval: 15s
      timeout: 15s
      retries: 1
      start_period: 15s
      disable: true

  couchdb:
    #image: couchdb:3
    # image: localhost/couchdb-docker
    image: ghcr.io/lorabridge2/couchdb-docker:latest
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    ports:
      - '5984:5984'
        #- '4369:4369'
        #- '9100:9100'
    restart: unless-stopped
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./couchdb/config.ini:/opt/couchdb/etc/local.d/10-config.ini
        # ro fails, as entrypoint script changes owner and group to couchdb user
        #user: 1337:1337
    networks:
      - loragatenet
  flow_manager:
    # build: gateway-device_manager
    image: ghcr.io/lorabridge2/gateway-flow-manager:latest
    environment:
      - DEV_MQTT_USERNAME=${MQTT_USERNAME}
      - DEV_MQTT_PASSWORD=${MQTT_PASSWORD}
      - DEV_MQTT_HOST=${MQTT_HOST}
      - DEV_MQTT_PORT=${MQTT_PORT}
      - DEV_REDIS_HOST=${REDIS_HOST}
      - DEV_REDIS_PORT=${REDIS_PORT}
      - DEV_REDIS_DB=${REDIS_DB}
      - DEV_EUI=${CHIRPSTACK_DEV_EUI}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - device:/device
    networks:
      - loragatenet
    depends_on:
      mosquitto:
        condition: service_started
      redis:
        condition: service_started
      chirp_helper:
        condition: service_completed_successfully
  chirp_helper:
    image: ghcr.io/lorabridge2/gateway-chirp-helper:latest
    environment:
      - CHIRP_HOST=chirpstack
      - CHIRP_PORT=8080
      - CHIRP_USER=${CHIRPSTACK_USER}
      - CHIRP_PASSWORD=${CHIRPSTACK_PASSWORD}
      - DEV_EUI=${CHIRPSTACK_DEV_EUI}
      - PYTHONUNBUFFERED=1
    restart: on-failure
    networks:
      - loragatenet
    depends_on:
      chirpstack:
        condition: service_started
    volumes:
      - token:/token
      - device:/device
  connection-watcher:
    image: ghcr.io/lorabridge2/gateway-connection-watcher:latest
    environment:
      - CHIRP_HOST=chirpstack
      - CHIRP_PORT=8080
      - DEV_EUI=${CHIRPSTACK_DEV_EUI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - PYTHONUNBUFFERED=1
    restart: on-failure
    networks:
      - loragatenet
    depends_on:
      chirpstack:
        condition: service_started
      redis:
        condition: service_started
      chirp_helper:
        condition: service_completed_successfully
    volumes:
      - token:/token
      - device:/device

volumes:
  redisdata:
  homeassistant_data:
  mdata:
  mlog:
  postgresqldata2:
  couchdb_data:
  token:
  device:
  gpio:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/sys/devices/platform/soc/soc:firmware/soc:firmware:gpio"

networks:
    loragatenet:
        attachable: true
        name: loragatenet
